
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password


development:
  <<: *default
  database: store_ecommerce_api_development

test:
  <<: *default
  database: store_ecommerce_api_test

production:
  <<: *default
  database: store_ecommerce_api_production
  username: store_ecommerce_api
  password: <%= ENV['STORE_ECOMMERCE_API_DATABASE_PASSWORD'] %>
